### ISSUE TITLE
Remove deprecated `gulp-util` module

### ISSUE THREAD

**Issue by strugee** [unifiedjs/unified-engine-gulp#18]
The `gulp-util` module is marked deprecated on npm and as such causes install warnings. It should be super easy to swap out; see [here](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5) for more information and equivalent functionality. If I have time I will probably do a PR for this one but feel free to take it now since I may not for a while.

**Comment by wooorm** [comment]
Good idea! PR would be lovely too, definitely! 👍

**Comment by strugee** [comment]
I definitely will PR if I have time! Which I may or may not since I'm in the middle of final exams ¯\_(ツ)_/¯

**Comment by wooorm** [comment]
Oh stressful! Well focus on that, and holiday season first!

Good luck with exams and take the time you need!
